### PR TITLE
Add fixes for Puppet 4 support

### PR DESCRIPTION
**Pull request by javierpena**
We need the remote::db class to be in a manifest named db.pp, and
there is no automated conversion of the $::operatingsystemmajrelease
fact to integer, unless we have an arithmetic operation.

### CODE REVIEW

**Comment by apolloliu** [comment]
Many methods to fix, I chose to use (versioncmp($::operatingsystemmajrelease, '7') <= 0).

**Comment by paramite** [comment]
Thanks for the patch! +1 for using versioncmp from stdlib instead. It seems cleaner to me. Otherwise patch is OK.

**Comment by apolloliu** [comment]
I have proposed https://github.com/paramite/puppet-remote/pull/6 to fix incorrect file.

**Comment by javierpena** [comment]
I've added a commit to use versioncmp. Actually, it doesn't require stdlib, according to [1]

[1] https://docs.puppet.com/puppet/3.6/function.html#versioncmp

**Pull request merged**
